### PR TITLE
Upped undertow version to 1.1.

### PR DESCRIPTION
**Pull request by dubiousdavid**

### CODE REVIEW

**Comment by piranha** [comment]
Yeah, why not. Thanks! :)

**Comment by piranha** [comment]
Sorry, I forgot my gpg key passphrase again. I'll sort this issue out and will publish new version a bit later. :)

**Comment by dubiousdavid** [comment]
Sounds good. Thanks.

**Comment by dubiousdavid** [comment]
Did you manage to deploy a new release yet?

**Comment by piranha** [comment]
I'm sorry it took so long! It's [there](https://clojars.org/ring-undertow-adapter).

**Pull request merged**
